name: 6D_pose_pf
channels:
  - defaults
dependencies:
  - python=3.10
  - blas
  - ca-certificates
  - certifi
  - freetype
  - intel-openmp
  - jpeg
  - lcms2
  - libffi
  - libgomp
  - libpng
  - ninja
  - numpy==1.23
  - olefile
  - openjpeg
  - openssl
  - pillow
  - zlib
  - zstd
  - opencv-python
  - transforms3d
  - open3d
  - scipy
  - scikit-image
  - mayavi
  - plyfile
  - filterpy
  - dipy
  - pycocotools
  - pyrealsense2
  - zmq
